# Build ftools Xronos binaries (`lcurve`, `powpowspec`, etc). These are not
# packaged for Debian, so they are compiled from source from
# https://heasarc.gsfc.nasa.gov/lheasoft/
# Adapted from https://github.com/bojobo/heasoft-docker/blob/main/Dockerfile
FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim AS heasoft_builder

ENV UV_NO_CACHE=1 \
    UV_SYSTEM_PYTHON=1

# Install HEASoft prerequisites
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get upgrade -y && apt-get dist-upgrade -y && \
    apt-get install -y --no-install-recommends \
    gcc \
    gfortran \
    g++ \
    curl \
    libcurl4 \
    libcurl4-gnutls-dev \
    libncurses5-dev \
    libreadline6-dev \
    libfile-which-perl \
    libdevel-checklib-perl \
    make \
    ncurses-dev \
    perl-modules \
    vim \
    wget \
    xorg-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /opt/heasoft

RUN uv pip install astropy numpy scipy matplotlib setuptools \
    && uv cache clean

ENV CC=/usr/bin/gcc CXX=/usr/bin/g++ FC=/usr/bin/gfortran
RUN unset CFLAGS CXXFLAGS FFLAGS LDFLAGS build_alias host_alias

# Retrieve the HEASoft source code via an a-la-carte link. Unfortunately, there
# doesn't seem to be a way to specify the version. This link was generated by
# visiting https://heasarc.gsfc.nasa.gov/docs/software/lheasoft/download-go.html
# and selecting Source code > PC - Linux - Debian, checking Xronos (only), and
# then Submit. The tar file download URL can be inspected in the browser.
RUN wget -O heasoft-src.tar.gz 'https://heasarc.gsfc.nasa.gov/cgi-bin/Tools/tarit/tarit.pl?mode=download&arch=src&src_pc_linux_debian=Y&src_other_specify=&xanadu=xronos'
RUN tar xfz heasoft-src.tar.gz

# Compile and install to /opt/heasoft.
RUN cd `ls -d heasoft-*/BUILD_DIR` \
    && ./configure --prefix=/opt/heasoft \
    && make \
    && make install

# Create links for /opt/heasoft/bin, /opt/heasoft/lib, etc.
RUN /bin/bash -c 'cd /opt/heasoft/; for loop in *64*/*; do ln -sf $loop; done'

# Use the standard JS9 base image.
FROM ghcr.io/js9-software/js9:v3.9.0

# Some of the ftools binaries need a fortran library. Since the builder and js9
# base images both use Debian, we can just get it again from the package repo.
RUN apt-get update && apt-get upgrade -y && apt-get dist-upgrade -y && \
    apt-get install -y --no-install-recommends \
    gfortran \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY --from=heasoft_builder /opt/heasoft /opt/heasoft

RUN mkdir /tmp/pfiles

RUN chmod a+wr /tmp/pfiles

RUN mkdir -p /opt/nso/bin

COPY ./bin /opt/nso/bin

ENV CC=/usr/bin/gcc \
    CXX=/usr/bin/g++ \
    FC=/usr/bin/gfortran \
    PERL=/usr/bin/perl \
    PERLLIB=/opt/heasoft/lib/perl \
    PERL5LIB=/opt/heasoft/lib/perl \
    PYTHON=/usr/bin/python \
    PYTHONPATH=/opt/heasoft/lib/python:/opt/heasoft/lib \
    PATH=/opt/heasoft/bin:/opt/nso/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    HEADAS=/opt/heasoft \
    LHEASOFT=/opt/heasoft \
    FTOOLS=/opt/heasoft \
    LD_LIBRARY_PATH=/opt/heasoft/lib \
    LHEAPERL=/usr/bin/perl \
    PFCLOBBER=1 \
    PFILES=/tmp/pfiles;/opt/heasoft/syspfiles \
    FTOOLSINPUT=stdin \
    FTOOLSOUTPUT=stdout \
    LHEA_DATA=/opt/heasoft/refdata \
    LHEA_HELP=/opt/heasoft/help \
    EXT=lnx \
    PGPLOT_FONT=/opt/heasoft/lib/grfont.dat \
    PGPLOT_RGB=/opt/heasoft/lib/rgb.txt \
    PGPLOT_DIR=/opt/heasoft/lib \
    POW_LIBRARY=/opt/heasoft/lib/pow \
    XRDEFAULTS=/opt/heasoft/xrdefaults \
    TCLRL_LIBDIR=/opt/heasoft/lib \
    XANADU=/opt/heasoft \
    XANBIN=/opt/heasoft \
    CALDB=https://heasarc.gsfc.nasa.gov/FTP/caldb
    # \ CALDBCONFIG=/opt/heasoft/caldb/caldb.config \
    # CALDBALIAS=/opt/heasoft/caldb/alias_config.fits

COPY ./index.html /app/web/index.html
COPY ./images /app/web/images
COPY ./css /app/web/css
COPY ./analysis-plugins/nsoAnalysis.json /app/web/analysis-plugins/nsoAnalysis.json
COPY ./analysis-wrappers/nsoXeq /app/web/analysis-wrappers/nsoXeq
COPY ./params /app/web/params
